language: java
jdk:
  - openjdk11
before_install:
  - chmod +x mvnw
  - psql -c 'CREATE DATABASE reviews;' -U postgres
  - psql -c 'CREATE ROLE ksv SUPERUSER LOGIN CREATEDB;' -U postgres
script:
  - mvn clean install
cache:
  directories:
    - $HOME/.m2
services:
  - postgresql
