version: "3"
services:
    app:
        build: .
        ports:
            - "8081:8081"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/reviews
        depends_on:
            - postgres
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=reviews
            - POSTGRES_USER=ksv
            - POSTGRES_PASSWORD=123
