version: '3.1'
services:
    app:
        container_name: springboot-boot-app
        image: spring-boot-app
        build: ./
        ports:
            - "8081:8081"
        depends_on:
            - dbpostgresql
    dbpostgresql:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=123
            - POSTGRES_USER=ksv
            - POSTGRES_DB=postgres
